# Generated by Django 3.2.21 on 2025-07-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Include country code, e.g. +91XXXXXXXXXX', max_length=15, null=True, unique=True, verbose_name='phone number'),
        ),
    ]
